sudo: false
language: node_js
node_js:
  - "6"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script: NODE_ENV=production yarn test